version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: '05:00'
      timezone: 'Asia/Taipei'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: 'Asia/Taipei'
